<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the public 'App\Controller\ApiController' shared autowired service.

include_once $this->targetDirs[3].'/src/Controller/ApiBaseController.php';
include_once $this->targetDirs[3].'/src/Controller/ApiController.php';
include_once $this->targetDirs[3].'/src/AppBundle/FourSquareApiAdapterBundle/Service/FourSquareAdapterBase.php';
include_once $this->targetDirs[3].'/src/AppBundle/FourSquareApiAdapterBundle/Service/FourSquareCategoryAdapterInterface.php';
include_once $this->targetDirs[3].'/src/AppBundle/FourSquareApiAdapterBundle/Service/FourSquareCategoryAdapter.php';
include_once $this->targetDirs[3].'/src/AppBundle/FourSquareApiAdapterBundle/Service/FoursquareConfigInterface.php';
include_once $this->targetDirs[3].'/src/AppBundle/FourSquareApiAdapterBundle/Service/FoursquareConfig.php';
include_once $this->targetDirs[3].'/src/AppBundle/FourSquareApiAdapterBundle/Service/FourSquareLocationAdapterInterface.php';
include_once $this->targetDirs[3].'/src/AppBundle/FourSquareApiAdapterBundle/Service/FourSquareLocationAdapter.php';

$a = new \App\AppBundle\FourSquareApiAdapterBundle\Service\FoursquareConfig(['clientId' => 'JNI4V4QH53WOEJDZ0ZGJZYKKV3QTLESO5SHY3VNOKSC1OYVZ', 'clientSecret' => 'NRALCBXP0EZJ4RQCSRYQQLC424UBCU2H2KSWJ3FWUOYH5PWR', 'baseUrl' => 'https://api.foursquare.com/v2', 'version' => '20180604']);

return $this->services['App\\Controller\\ApiController'] = new \App\Controller\ApiController(new \App\AppBundle\FourSquareApiAdapterBundle\Service\FourSquareCategoryAdapter($a), new \App\AppBundle\FourSquareApiAdapterBundle\Service\FourSquareLocationAdapter($a));
