<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_api_categorylist' => [[], ['_controller' => 'App\\Controller\\ApiController::categoryListAction'], [], [['text', '/api/v1/categories']], [], []],
    'locations' => [['categoryName'], ['_controller' => 'App\\Controller\\ApiController::locationListAction'], [], [['variable', '/', '[^/]++', 'categoryName', true], ['text', '/api/v1/locations']], [], []],
];
